name: nsc2026
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.15.3=hb03c661_0
  - aws-c-auth=0.9.3=hef928c7_0
  - aws-c-cal=0.9.13=h2c9d079_1
  - aws-c-common=0.12.6=hb03c661_0
  - aws-c-compression=0.3.1=h8b1a151_9
  - aws-c-event-stream=0.5.7=h28f887f_1
  - aws-c-http=0.10.7=ha8fc4e3_5
  - aws-c-io=0.23.3=hdaf4b65_5
  - aws-c-mqtt=0.13.3=hc63082f_11
  - aws-c-s3=0.11.3=h06ab39a_1
  - aws-c-sdkutils=0.2.4=h8b1a151_4
  - aws-checksums=0.2.7=h8b1a151_5
  - aws-crt-cpp=0.35.4=h8824e59_0
  - aws-sdk-cpp=1.11.606=h20b40b1_10
  - azure-core-cpp=1.16.1=h3a458e0_0
  - azure-identity-cpp=1.13.2=h3a5f585_1
  - azure-storage-blobs-cpp=12.16.0=h75daedc_0
  - azure-storage-common-cpp=12.12.0=h3d7a050_0
  - azure-storage-files-datalake-cpp=12.14.0=hd454692_0
  - backports.zstd=1.3.0=py311h6b1f9c4_0
  - bokeh=3.8.2=pyhd8ed1ab_0
  - brotli=1.2.0=hed03a55_1
  - brotli-bin=1.2.0=hb03c661_1
  - brotli-python=1.2.0=py311h66f275b_1
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.18.4=he90730b_1
  - click=8.3.1=pyh8f84b5b_1
  - cloudpickle=3.1.2=pyhcf101f3_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.3=py311h724c32c_4
  - cycler=0.12.1=pyhcf101f3_2
  - cyrus-sasl=2.1.28=hd9c7081_0
  - cytoolz=1.1.0=py311h49ec1c0_1
  - dask=2026.1.2=pyhcf101f3_0
  - dask-core=2026.1.2=pyhcf101f3_0
  - dbus=1.16.2=h24cb091_1
  - distributed=2026.1.2=pyhcf101f3_0
  - double-conversion=3.4.0=hecca717_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=py311h3778330_0
  - freetype=2.14.1=ha770c72_0
  - fsspec=2026.1.0=pyhd8ed1ab_0
  - gflags=2.2.2=h5888daf_1005
  - glog=0.7.1=hbabe93e_0
  - graphite2=1.3.14=hecca717_2
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.3.2=h6083320_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=78.2=h33c6efd_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - iniconfig=2.3.0=pyhd8ed1ab_0
  - jinja2=3.1.6=pyhcf101f3_1
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py311h724c32c_2
  - krb5=1.21.3=h659f571_0
  - lcms2=2.18=h0c24ade_0
  - ld_impl_linux-64=2.45.1=default_hbd61a6d_101
  - lerc=4.0.0=h0aef613_1
  - libabseil=20250512.1=cxx17_hba17884_0
  - libarrow=23.0.0=h2c50142_1_cpu
  - libarrow-acero=23.0.0=h635bf11_1_cpu
  - libarrow-compute=23.0.0=h8c2c5c3_1_cpu
  - libarrow-dataset=23.0.0=h635bf11_1_cpu
  - libarrow-substrait=23.0.0=h3f74fd7_1_cpu
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libbrotlicommon=1.2.0=hb03c661_1
  - libbrotlidec=1.2.0=hb03c661_1
  - libbrotlienc=1.2.0=hb03c661_1
  - libcblas=3.11.0=5_h0358290_openblas
  - libclang-cpp21.1=21.1.8=default_h99862b1_3
  - libclang13=21.1.8=default_h746c552_3
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.18.0=h4e3cde8_0
  - libdeflate=1.25=h17f619e_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h3435931_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_17
  - libgcc-ng=15.2.0=h69a702a_17
  - libgfortran=15.2.0=h69a702a_17
  - libgfortran5=15.2.0=h68bc16d_17
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.86.3=h6548e54_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=he0feb66_17
  - libgoogle-cloud=2.39.0=hdb79228_0
  - libgoogle-cloud-storage=2.39.0=hdbdcf42_0
  - libgrpc=1.73.1=h3288cfb_1
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblapack=3.11.0=5_h47877c9_openblas
  - libllvm21=21.1.8=hf7376ad_0
  - liblzma=5.8.2=hb03c661_0
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libopengl=1.7.0=ha4b6fd6_2
  - libopentelemetry-cpp=1.21.0=hb9b0907_1
  - libopentelemetry-cpp-headers=1.21.0=ha770c72_1
  - libparquet=23.0.0=h7376487_1_cpu
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.54=h421ea60_0
  - libpq=18.1=hb80d175_3
  - libprotobuf=6.31.1=h49aed37_4
  - libre2-11=2025.11.05=h7b12aa8_0
  - libsqlite=3.51.2=hf4e2dac_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h934c35e_17
  - libstdcxx-ng=15.2.0=hdf11a46_17
  - libthrift=0.22.0=h454ac66_1
  - libtiff=4.7.1=h9d88235_1
  - libutf8proc=2.11.3=hfe17d71_0
  - libuuid=2.41.3=h5347b49_0
  - libvulkan-loader=1.4.341.0=h5279c79_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.13.1=hca5e8e5_0
  - libxml2=2.15.1=he237659_1
  - libxml2-16=2.15.1=hca6bf5a_1
  - libxslt=1.1.43=h711ed8c_1
  - libzlib=1.3.1=hb9d3cd8_2
  - llvmlite=0.46.0=py311h41a00d4_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.4.5=py311h1c460e0_1
  - lz4-c=1.10.0=h5888daf_1
  - markupsafe=3.0.3=py311h3778330_0
  - matplotlib=3.10.8=py311h38be061_0
  - matplotlib-base=3.10.8=py311h0f3be63_0
  - msgpack-python=1.1.2=py311hdf67eae_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - narwhals=2.16.0=pyhcf101f3_0
  - ncurses=6.5=h2d0b736_3
  - nlohmann_json=3.12.0=h54a6638_1
  - numba=0.63.1=py311h3c884d5_0
  - numpy=2.3.5=py311h2e04523_1
  - openjpeg=2.5.4=h55fea9a_0
  - openldap=2.6.10=he970967_0
  - openssl=3.6.1=h35e630c_1
  - orc=2.2.2=h19cb568_0
  - packaging=26.0=pyhcf101f3_0
  - pandas=3.0.0=py311h8032f78_0
  - partd=1.4.2=pyhd8ed1ab_0
  - pcre2=10.47=haa7fec5_0
  - pillow=12.1.0=py311hf88fc01_0
  - pip=26.0.1=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - pluggy=1.6.0=pyhf9edf01_1
  - prometheus-cpp=1.3.0=ha5d0236_0
  - psutil=7.2.2=py311haee01d2_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pyarrow=23.0.0=py311h38be061_0
  - pyarrow-core=23.0.0=py311h342b5a4_0_cpu
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.3.2=pyhcf101f3_0
  - pyside6=6.10.2=py311he4c1a5a_0
  - pysocks=1.7.1=pyha55dd90_7
  - pytest=9.0.2=pyhcf101f3_0
  - python=3.11.14=hd63d673_3_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.11=8_cp311
  - pyyaml=6.0.3=py311h3778330_1
  - qhull=2020.2=h434a139_5
  - qt6-main=6.10.2=hb82b983_4
  - re2=2025.11.05=h5301d42_0
  - readline=8.3=h853b02a_0
  - s2n=1.6.2=he8a4886_1
  - scipy=1.17.0=py311hbe70eeb_1
  - setuptools=80.10.2=pyh332efcf_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h03e3b7b_1
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - tblib=3.2.2=pyhcf101f3_0
  - tk=8.6.13=noxft_h366c992_103
  - tomli=2.4.0=pyhcf101f3_0
  - toolz=1.1.0=pyhd8ed1ab_1
  - tornado=6.5.4=py311h41d9c34_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=hc9c84f9_1
  - unicodedata2=17.0.0=py311h49ec1c0_1
  - urllib3=2.6.3=pyhd8ed1ab_0
  - wayland=1.24.0=hd6090a7_1
  - wheel=0.46.3=pyhd8ed1ab_0
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.6=hb03c661_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxcomposite=0.4.7=hb03c661_0
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.7=hb03c661_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.5=hb03c661_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.7=hb03c661_0
  - xyzservices=2025.11.0=pyhd8ed1ab_0
  - yaml=0.2.5=h280c20c_3
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=hb9d3cd8_2
  - zlib-ng=2.3.3=hceb46e0_1
  - zstd=1.5.7=hb78ec9c_6

prefix: "/home/snorre/miniforge3/envs/nsc2026"
